import {
  Study,
  Persona,
  StudyApplication,
  StudyReminder,
  PIData,
  ParticipantTask,
  ParticipantConsent,
  AppNotification,
} from "./types";

export const DEMO_PERSONAS: Record<string, Persona> = {
  rural_male: {
    id: "rural_male",
    name: "Marcus Davis",
    roleDescription: "Healthy Volunteer • Sanford, NC",
    badgeLabel: "Rural Male (diversity target)",
    profile: {
      id: "prof_marcus",
      fullName: "Marcus Davis",
      email: "marcus.davis92@example.com",
      phone: "919-555-0144",
      age: 58,
      gender: "male",
      educationLevel: "high_school_or_less",
      livingEnvironment: "rural",
      city: "Sanford",
      state: "NC",
      zipCode: "27330",
      travelDistanceMiles: 45,
      isHealthyVolunteer: true,
      conditions: [],
      medications: [],
      hasRecentAntibiotics: false,
      smokerStatus: "never",
      avatarInitials: "MD",
      tagline: "Prioritizing flexible morning visits within 45 miles of Sanford.",
      preferredContactMethod: "phone",
      isContactVerified: true,
      preferredLocationType: "in_person",
      preferredLanguage: "English",
      transportationAccess: "personal_vehicle",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
  urban_student: {
    id: "urban_student",
    name: "Chloe Martinez",
    roleDescription: "Healthy Student • Durham, NC",
    badgeLabel: "Urban Student (healthy-control)",
    profile: {
      id: "prof_chloe",
      fullName: "Chloe Martinez",
      email: "chloe.m.student@example.edu",
      phone: "919-555-0189",
      age: 23,
      gender: "female",
      educationLevel: "bachelors",
      livingEnvironment: "urban",
      city: "Durham",
      state: "NC",
      zipCode: "27701",
      travelDistanceMiles: 15,
      isHealthyVolunteer: true,
      conditions: [],
      medications: [],
      hasRecentAntibiotics: false,
      smokerStatus: "never",
      avatarInitials: "CM",
      tagline: "Duke/UNC area student seeking afternoon and weekend research studies.",
      preferredContactMethod: "email",
      isContactVerified: true,
      preferredLocationType: "hybrid",
      preferredLanguage: "English",
      transportationAccess: "public_transit",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
  chronic_patient: {
    id: "chronic_patient",
    name: "Robert Chen",
    roleDescription: "Type 2 Diabetes Patient • Cary, NC",
    badgeLabel: "Type 2 Diabetes Patient",
    profile: {
      id: "prof_robert",
      fullName: "Robert Chen",
      email: "robert.chen.t2d@example.org",
      phone: "919-555-0219",
      age: 52,
      gender: "male",
      educationLevel: "graduate_degree",
      livingEnvironment: "suburban",
      city: "Cary",
      state: "NC",
      zipCode: "27513",
      travelDistanceMiles: 25,
      isHealthyVolunteer: false,
      conditions: ["Type 2 Diabetes", "Mild Hypertension"],
      medications: ["Metformin 500mg"],
      hasRecentAntibiotics: false,
      smokerStatus: "former",
      avatarInitials: "RC",
      tagline: "Managing stable T2D for 4 years, interested in novel metabolic trials.",
      preferredContactMethod: "email",
      isContactVerified: true,
      preferredLocationType: "in_person",
      preferredLanguage: "English",
      transportationAccess: "personal_vehicle",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
  senior_control: {
    id: "senior_control",
    name: "Dr. Evelyn Harper",
    roleDescription: "Healthy Senior Control • Chapel Hill, NC",
    badgeLabel: "Senior Volunteer (geriatric cohort)",
    profile: {
      id: "prof_evelyn",
      fullName: "Dr. Evelyn Harper",
      email: "evelyn.harper.retired@example.edu",
      phone: "919-555-0211",
      age: 71,
      gender: "female",
      educationLevel: "graduate_degree",
      livingEnvironment: "suburban",
      city: "Chapel Hill",
      state: "NC",
      zipCode: "27514",
      travelDistanceMiles: 20,
      isHealthyVolunteer: true,
      conditions: [],
      medications: [],
      hasRecentAntibiotics: false,
      smokerStatus: "never",
      avatarInitials: "EH",
      tagline: "Retired educator passionate about cognitive longevity research.",
      preferredContactMethod: "phone",
      isContactVerified: true,
      preferredLocationType: "in_person",
      preferredLanguage: "English",
      transportationAccess: "personal_vehicle",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
  respiratory_patient: {
    id: "respiratory_patient",
    name: "Darius Washington",
    roleDescription: "Asthma Participant • Raleigh, NC",
    badgeLabel: "Respiratory Patient (pulmonary target)",
    profile: {
      id: "prof_darius",
      fullName: "Darius Washington",
      email: "darius.washington90@example.com",
      phone: "919-555-0245",
      age: 34,
      gender: "male",
      educationLevel: "bachelors",
      livingEnvironment: "urban",
      city: "Raleigh",
      state: "NC",
      zipCode: "27601",
      travelDistanceMiles: 30,
      isHealthyVolunteer: false,
      conditions: ["Mild Persistent Asthma", "Seasonal Allergic Rhinitis"],
      medications: ["Albuterol Inhaler", "Fluticasone"],
      hasRecentAntibiotics: false,
      smokerStatus: "never",
      avatarInitials: "DW",
      tagline: "Tech worker with controlled asthma interested in sensor & wearable studies.",
      preferredContactMethod: "sms",
      isContactVerified: true,
      preferredLocationType: "hybrid",
      preferredLanguage: "English",
      transportationAccess: "rideshare",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
  bilingual_caregiver: {
    id: "bilingual_caregiver",
    name: "Maria Santos",
    roleDescription: "Bilingual Caregiver • Burlington, NC",
    badgeLabel: "Hispanic Caregiver (diversity target)",
    profile: {
      id: "prof_maria",
      fullName: "Maria Santos",
      email: "maria.santos.crc@example.org",
      phone: "919-555-0278",
      age: 46,
      gender: "female",
      educationLevel: "some_college",
      livingEnvironment: "suburban",
      city: "Burlington",
      state: "NC",
      zipCode: "27215",
      travelDistanceMiles: 35,
      isHealthyVolunteer: false,
      conditions: ["Essential Hypertension"],
      medications: ["Lisinopril 10mg"],
      hasRecentAntibiotics: false,
      smokerStatus: "never",
      avatarInitials: "MS",
      tagline: "Family caregiver advocating for bilingual health trial access.",
      preferredContactMethod: "phone",
      isContactVerified: true,
      preferredLocationType: "in_person",
      preferredLanguage: "Spanish",
      transportationAccess: "personal_vehicle",
      accessibilityNeeds: undefined,
      hasCaregiver: true,
      hasInternetSmartphone: true,
    },
  },
  veteran_volunteer: {
    id: "veteran_volunteer",
    name: "James 'Jim' O'Connor",
    roleDescription: "Military Veteran • Fayetteville, NC",
    badgeLabel: "Rural Veteran (sleep/circadian cohort)",
    profile: {
      id: "prof_jim",
      fullName: "James 'Jim' O'Connor",
      email: "jim.oconnor.usmc@example.com",
      phone: "919-555-0312",
      age: 62,
      gender: "male",
      educationLevel: "some_college",
      livingEnvironment: "rural",
      city: "Fayetteville",
      state: "NC",
      zipCode: "28301",
      travelDistanceMiles: 50,
      isHealthyVolunteer: false,
      conditions: ["Insomnia", "Mild Tinnitus"],
      medications: ["Melatonin 5mg"],
      hasRecentAntibiotics: false,
      smokerStatus: "former",
      avatarInitials: "JO",
      tagline: "USMC veteran interested in sleep medicine & circadian telemetry.",
      preferredContactMethod: "phone",
      isContactVerified: true,
      preferredLocationType: "in_person",
      preferredLanguage: "English",
      transportationAccess: "personal_vehicle",
      accessibilityNeeds: undefined,
      hasCaregiver: false,
      hasInternetSmartphone: true,
    },
  },
};

export const PROTOCOL_STUDIES: Study[] = [
  {
    id: "study_1",
    slug: "healthy-aging-sensory-resilience-study",
    title: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    sponsorName: "Triangle Aging & Brain Sciences Center",
    sponsorType: "university",
    piName: "Dr. H. Whitman, MD",
    piTitle: "Professor of Medicine & Director, Triangle Center for Aging",
    studyType: "cognitive_assessment",
    compensationAmount: 650,
    compensationType: "Direct Deposit / Visa Card",
    compensationSchedule: "$150 per visit (3 visits) + $200 completion bonus upon exit interview",
    timeCommitment: "3 visits over 6 weeks (1.5 hrs/visit)",
    durationWeeks: 6,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Triangle Clinical Research Pavilion, Durham, NC 27710",
    summary: "Investigating how combined visual and hearing cues affect cognitive resilience in older adults. Actively seeking men and rural participants to meet representation quotas.",
    fullDescription: "Our goal is to understand how the brain adapts to subtle sensory variations as we grow older. Participants undergo safe, non-invasive sensory tests and brief memory problem-solving activities on a tablet. You are compensated for each visit attended with full travel mileage reimbursements.",
    irbApprovalNumber: "Pro00109482",
    targetEnrollment: 120,
    currentEnrolled: 54,
    minAge: 50,
    maxAge: 85,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Severe Dementia", "Active Stroke within 6 months"],
    targetDemographicFocus: "Actively seeking rural residents, non-college educated volunteers, and men to achieve representative 40% male enrollment target.",
    isFeatured: true,
    isSponsored: true,
    questions: [
      {
        id: "q1_1",
        questionText: "Are you between the ages of 50 and 85?",
        explanation: "Protocol is strictly designed for adults aged 50+",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Participants must be at least 50 years of age.",
      },
      {
        id: "q1_2",
        questionText: "Have you had a stroke or traumatic brain injury within the past 6 months?",
        explanation: "Recent acute neurological trauma can skew baseline sensory test data",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Recent neurological incidents exclude participation during acute recovery phase.",
      },
      {
        id: "q1_3",
        questionText: "Can you attend 3 scheduled in-person morning visits at the Triangle Clinical Pavilion in Durham, NC?",
        explanation: "Visits include timed reflex assessments in the lab",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Must be able to attend all 3 on-site visits in Durham.",
      },
      {
        id: "q1_4",
        questionText: "Do you have severe uncorrectable vision loss (e.g., total legal blindness)?",
        explanation: "Participants must be able to view basic shapes on a standard display",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Visual tasks require baseline ability to discern shapes on screen.",
      },
    ],
  },
  {
    id: "study_2",
    slug: "healthy-volunteer-immunology-blood-profile",
    title: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    sponsorName: "Triangle Thoracic & Surgical Immunology Lab",
    sponsorType: "hospital",
    piName: "Dr. Rachel Aris, MD, PhD",
    piTitle: "Chief of Cellular Immunology",
    studyType: "blood_draw",
    compensationAmount: 250,
    compensationType: "Direct Bank Deposit",
    compensationSchedule: "$100 for Visit 1 + $150 for Visit 2 (completed within 14 days)",
    timeCommitment: "2 visits (45 mins each, 2 weeks apart)",
    durationWeeks: 2,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Hospital South Clinics, Phlebotomy Core 3B, Durham, NC 27705",
    summary: "Routine fasting blood draws two weeks apart to establish baseline lymphocyte reference data for surgical organ transplant science.",
    fullDescription: "Healthy volunteers provide approximately 35ml of venous blood across two scheduled mornings. Blood samples help researchers measure natural lymphocyte population fluctuations to build control datasets for heart and kidney transplant rejection monitors.",
    irbApprovalNumber: "IRB-2026-00412",
    targetEnrollment: 60,
    currentEnrolled: 38,
    minAge: 18,
    maxAge: 70,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Active Cancer", "HIV", "Hepatitis C", "Immunosuppressive Medications"],
    targetDemographicFocus: "General healthy adult population in the Triangle area.",
    isFeatured: false,
    isSponsored: false,
    questions: [
      {
        id: "q2_1",
        questionText: "Have you taken oral antibiotics, steroids, or prescription anti-inflammatory drugs in the last 30 days?",
        explanation: "Antibiotics alter immune cell expression and cytokine baseline values",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Must be free from oral antibiotics for at least 30 days.",
      },
      {
        id: "q2_2",
        questionText: "Do you have any diagnosed blood clotting disorders or severe vasovagal syncope during routine blood draws?",
        explanation: "Ensures volunteer safety during venous phlebotomy",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Safety protocol requires tolerance of standard phlebotomy.",
      },
      {
        id: "q2_3",
        questionText: "Are you willing to complete an overnight fast (water permitted) prior to both morning appointments?",
        explanation: "Fasting lipid and glucose levels normalize immune markers",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Fasting protocol is required for valid biomarker measurement.",
      },
    ],
  },
  {
    id: "study_3",
    slug: "national-digital-sleep-circadian-study",
    title: "National Digital Sleep & Circadian Rhythm Study",
    sponsorName: "BioVanguard Digital Health Institute",
    sponsorType: "research_center",
    piName: "Dr. Marcus Sterling, PhD",
    piTitle: "Head of Behavioral Sleep Medicine",
    studyType: "observational_survey",
    compensationAmount: 320,
    compensationType: "Stipend + Keep Device ($299 value)",
    compensationSchedule: "$50 onboarding + $120 midway log bonus + $150 exit stipend + smart ring",
    timeCommitment: "10 mins/day for 6 weeks (100% Remote)",
    durationWeeks: 6,
    locationType: "remote",
    city: "Nationwide",
    state: "US",
    facilityAddress: "Remote - All sensors shipped directly to home address with prepaid return labels.",
    summary: "Wear a provided medical-grade smart ring to bed each night and log quick morning energy ratings. 100% remote observational study with no clinic visits.",
    fullDescription: "Investigating how subtle nighttime environmental factors (ambient temperature, micro-awakenings) influence cognitive clarity and perceived energy levels throughout the workday. You will be shipped a smart ring to wear each evening and complete brief 2-minute daily check-ins on your mobile phone.",
    irbApprovalNumber: "WCG-IRB-2025-9981",
    targetEnrollment: 500,
    currentEnrolled: 312,
    minAge: 21,
    maxAge: 65,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Severe Obstructive Sleep Apnea on CPAP", "Night Shift Work"],
    targetDemographicFocus: "Adults working standard daytime shifts across all US zip codes.",
    isFeatured: true,
    isSponsored: false,
    questions: [
      {
        id: "q3_1",
        questionText: "Do you own and actively use an iOS or Android smartphone with Bluetooth 5.0+?",
        explanation: "Required to sync nighttime sensor metrics with study database",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "A compatible smartphone is required for sensor data synchronization.",
      },
      {
        id: "q3_2",
        questionText: "Do you work rotating overnight shifts (e.g., night nurse, overnight manufacturing)?",
        explanation: "Trial specifically studies regular circadian biological patterns",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Protocol requires non-overnight daytime sleep-wake cycles.",
      },
      {
        id: "q3_3",
        questionText: "Have you been formally diagnosed with untreated severe Obstructive Sleep Apnea?",
        explanation: "Severe respiratory apnea masks circadian variations",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Untreated sleep apnea confounds nocturnal biometric measurements.",
      },
    ],
  },
  {
    id: "study_4",
    slug: "phase-2-oral-glp1-diabetes-trial",
    title: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist Trial",
    sponsorName: "Apex Pharma Therapeutics",
    sponsorType: "pharma",
    piName: "Dr. Elena Vance, MD",
    piTitle: "Vice Chair of Clinical Endocrinology",
    studyType: "clinical_trial",
    compensationAmount: 1850,
    compensationType: "Electronic Funds Transfer",
    compensationSchedule: "$150 per monthly visit (6 visits) + $950 completion milestone stipend",
    timeCommitment: "Monthly visit for 24 weeks + weekly home glucose log",
    durationWeeks: 24,
    locationType: "in_person",
    city: "Raleigh",
    state: "NC",
    facilityAddress: "Apex Clinical Trials Center, Suite 400, Raleigh, NC 27607",
    summary: "Evaluating a next-generation once-weekly oral GLP-1 tablet for adults managing Type 2 Diabetes with metformin or lifestyle alone.",
    fullDescription: "Phase II, randomized, double-blind clinical trial evaluating the safety, pharmacokinetics, and glycemic control of a novel oral once-weekly GLP-1 receptor agonist compared to standard therapies. All study-related lab tests, medical exams, continuous glucose monitors, and study medication are provided at no cost.",
    irbApprovalNumber: "Advarra-IRB-2026-0182",
    targetEnrollment: 80,
    currentEnrolled: 29,
    minAge: 35,
    maxAge: 75,
    targetGender: "all",
    healthyVolunteersAccepted: false,
    requiredConditions: ["Type 2 Diabetes"],
    excludedConditions: ["Type 1 Diabetes", "History of Pancreatitis", "eGFR < 30"],
    targetDemographicFocus: "Adults with confirmed Type 2 Diabetes for at least 6 months.",
    isFeatured: true,
    isSponsored: true,
    questions: [
      {
        id: "q4_1",
        questionText: "Have you been diagnosed by a physician with Type 2 Diabetes for at least 6 months?",
        explanation: "Study evaluates therapeutic intervention specifically for Type 2 Diabetes",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Trial requires established diagnosis of Type 2 Diabetes.",
      },
      {
        id: "q4_2",
        questionText: "Do you have a personal or immediate family history of medullary thyroid carcinoma or pancreatitis?",
        explanation: "Known exclusion criteria for GLP-1 receptor class therapeutics",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Personal or family history of pancreatitis excludes GLP-1 trial participation.",
      },
      {
        id: "q4_3",
        questionText: "Are you currently taking injectable insulin therapy on a daily basis?",
        explanation: "Participants should be managed on oral medications (e.g. metformin) or lifestyle alone",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Current insulin dependency is an exclusion for this Phase II cohort.",
      },
      {
        id: "q4_4",
        questionText: "Can you attend monthly morning check-up visits at the Apex Trials Center in Raleigh, NC?",
        explanation: "In-person visits required for safety lab panels and HbA1c assays",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Must be able to attend on-site visits in Raleigh, NC.",
      },
    ],
  },
  {
    id: "study_5",
    slug: "fmri-risk-evaluation-financial-decisions",
    title: "Neuroimaging of Risk Evaluation & Financial Decisions",
    sponsorName: "Carolina Institute for Neuroeconomics",
    sponsorType: "university",
    piName: "Dr. Julian Thorne, PhD",
    piTitle: "Associate Professor of Behavioral Economics & Cognitive Neuroscience",
    studyType: "imaging_mri",
    compensationAmount: 350,
    compensationType: "Instant Cash / Venmo",
    compensationSchedule: "$150 upon completion of scan + up to $200 performance bonus based on decision game",
    timeCommitment: "Single 3.5-hour afternoon session",
    durationWeeks: 1,
    locationType: "in_person",
    city: "Chapel Hill",
    state: "NC",
    facilityAddress: "Biomedical Research Imaging Center (BRIC), Chapel Hill, NC 27599",
    summary: "High-resolution 3-Tesla fMRI neuroimaging while playing realistic financial decision and asset allocation games on an MRI-safe controller.",
    fullDescription: "Investigating how frontostriatal brain circuits process probability, loss aversion, and delayed rewards under varying market volatility. Participants complete a harmless 75-minute MRI scan while responding to simulated financial investment scenarios.",
    irbApprovalNumber: "UNC-IRB-25-0814",
    targetEnrollment: 45,
    currentEnrolled: 31,
    minAge: 21,
    maxAge: 45,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Ferrous Metal Implants", "Pacemakers", "Severe Claustrophobia"],
    targetDemographicFocus: "Healthy young and middle-aged adults without metal implants.",
    isFeatured: false,
    isSponsored: false,
    questions: [
      {
        id: "q5_1",
        questionText: "Do you have any metallic implants, pacemakers, surgical clips, or metal fragments in your body?",
        explanation: "High magnetic field (3-Tesla) strictly prohibits any ferromagnetic material",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Ferrous metallic implants are an absolute safety contraindication for MRI.",
      },
      {
        id: "q5_2",
        questionText: "Do you experience severe claustrophobia or panic in enclosed spaces?",
        explanation: "fMRI scanner requires laying still inside a cylindrical bore for 75 minutes",
        expectedAnswer: "no",
        isDisqualifying: true,
        disqualificationReason: "Participants must be comfortable remaining still inside an MRI scanner.",
      },
      {
        id: "q5_3",
        questionText: "Are you between the ages of 21 and 45?",
        explanation: "Cohort targets peak working-age financial decision makers",
        expectedAnswer: "yes",
        isDisqualifying: true,
        disqualificationReason: "Age must be between 21 and 45 for this protocol.",
      },
    ],
  },
];

export const INITIAL_APPLICATIONS: StudyApplication[] = [
  // Marcus Davis on Study 1 (Sensory resilience) -> action_needed
  {
    id: "app_1",
    studyId: "study_1",
    profileId: "prof_marcus",
    studyTitle: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    sponsorName: "Triangle Aging & Brain Sciences Center",
    compensationAmount: 650,
    status: "action_needed",
    qualificationScore: 100,
    answers: { q1_1: "yes", q1_2: "no", q1_3: "yes", q1_4: "no" },
    researcherNotes: "Qualified site handoff complete. Participant Marcus Davis prioritized under rural male quota.",
    participantFacingNote: "Please confirm your availability for the baseline sensory intake session with Coordinator Sarah.",
    internalStaffNote: "Eligible for 40% male balancing quota. Travel stipend calculated for Sanford, NC.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 14, 10:30 AM",
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: "Sep 24 at 1:00 PM",
    createdAt: "Sep 02, 2:22 PM",
  },
  // Marcus Davis on Study 2 (Immunology blood profile) -> enrolled
  {
    id: "app_2",
    studyId: "study_2",
    profileId: "prof_marcus",
    studyTitle: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    sponsorName: "Triangle Thoracic & Surgical Immunology Lab",
    compensationAmount: 250,
    status: "enrolled",
    qualificationScore: 100,
    answers: { q2_1: "no", q2_2: "no", q2_3: "yes" },
    researcherNotes: "First venous blood draw booked at Triangle Hospital Phlebotomy Core 3B.",
    participantFacingNote: "Enrolled in Phase A. Visit 1 completed on Sept 10. Visit 2 scheduled for Sept 24.",
    internalStaffNote: "Consent signed on file. Blood draw tubes stored at -80C core freezer.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 10, 11:00 AM",
    lastStatusChangedByName: "Dr. H. Whitman, MD",
    appointmentDate: "Sep 24 at 9:00 AM",
    createdAt: "Aug 28, 9:15 AM",
  },
  // Marcus Davis on Study 3 (Sleep Observational) -> under_review
  {
    id: "app_3",
    studyId: "study_3",
    profileId: "prof_marcus",
    studyTitle: "National Digital Sleep & Circadian Rhythm Study",
    sponsorName: "BioVanguard Digital Health Institute",
    compensationAmount: 320,
    status: "under_review",
    qualificationScore: 100,
    answers: { q3_1: "yes", q3_2: "no", q3_3: "no" },
    researcherNotes: "Hardware dispatch queue pending sensor batch allocation.",
    participantFacingNote: "Application submitted. The digital research team is preparing your smart ring sensor kit for shipping.",
    internalStaffNote: "Mailing address validated with USPS core API.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 12, 3:00 PM",
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: "Hardware in transit",
    createdAt: "Sep 05, 6:40 PM",
  },
  // Marcus Davis on Study 4 (Oral GLP-1) -> not_selected (with respectful guidance)
  {
    id: "app_4",
    studyId: "study_4",
    profileId: "prof_marcus",
    studyTitle: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist Trial",
    sponsorName: "Apex Pharma Therapeutics",
    compensationAmount: 1850,
    status: "not_selected",
    qualificationScore: 40,
    answers: { q4_1: "no", q4_2: "no" },
    disqualificationNotes: "Requires diagnosed Type 2 Diabetes or documented metabolic syndrome.",
    researcherNotes: "Healthy volunteer applied to condition-specific trial.",
    participantFacingNote: "Thank you for your application. Because this study requires a diagnosed metabolic condition (Type 2 Diabetes), your profile was not selected for this protocol. Please explore our alternative healthy volunteer studies below.",
    internalStaffNote: "Respectful decline sent with recommendations.",
    statusUpdatedAt: "Sep 08, 9:20 AM",
    lastStatusChangedByName: "Dr. Elena Vance, MD",
    createdAt: "Sep 06, 11:30 AM",
  },
  // Chloe Martinez on Study 5 (fMRI Brain Mapping) -> eligible_next_step
  {
    id: "app_5",
    studyId: "study_5",
    profileId: "prof_chloe",
    studyTitle: "Neuroimaging of Risk Evaluation & Financial Decisions",
    sponsorName: "Carolina Institute for Neuroeconomics",
    compensationAmount: 350,
    status: "eligible_next_step",
    qualificationScore: 100,
    answers: { q5_1: "no", q5_2: "no", q5_3: "yes" },
    researcherNotes: "3T MRI safety checklist passed. No ferromagnetic implants or claustrophobia.",
    participantFacingNote: "Pre-screen verified! You are eligible to book your 2.5-hour fMRI scan session at Chapel Hill.",
    internalStaffNote: "Safety clearance signed off by Dr. Sterling.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 15, 2:10 PM",
    lastStatusChangedByName: "Dr. H. Whitman, MD",
    appointmentDate: "Sep 26 at 2:00 PM",
    createdAt: "Sep 04, 12:00 PM",
  },
  // Robert Chen on Study 4 (Oral GLP-1) -> enrolled
  {
    id: "app_6",
    studyId: "study_4",
    profileId: "prof_robert",
    studyTitle: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist Trial",
    sponsorName: "Apex Pharma Therapeutics",
    compensationAmount: 1850,
    status: "enrolled",
    qualificationScore: 100,
    answers: { q4_1: "yes", q4_2: "no", q4_3: "no", q4_4: "yes" },
    researcherNotes: "Baseline HbA1c 7.9% verified. Study drug kit #104 dispensed.",
    participantFacingNote: "Active participant in Phase II Oral GLP-1 Trial. Next clinic follow-up scheduled for October 4.",
    internalStaffNote: "Informed consent v3 signed. Fasting lipids and glucose normal at baseline.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 11, 4:00 PM",
    lastStatusChangedByName: "Dr. Elena Vance, MD",
    appointmentDate: "Oct 04 at 10:00 AM",
    createdAt: "Aug 30, 10:15 AM",
  },
  // Evelyn Harper on study_1 (Sensory resilience) -> enrolled
  {
    id: "app_7",
    studyId: "study_1",
    profileId: "prof_evelyn",
    studyTitle: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    sponsorName: "Triangle Aging & Brain Sciences Center",
    compensationAmount: 650,
    status: "enrolled",
    qualificationScore: 100,
    answers: { q1_1: "yes", q1_2: "no", q1_3: "yes", q1_4: "no" },
    researcherNotes: "Senior healthy control volunteer (71 yo). Perfect baseline cognitive assessment.",
    participantFacingNote: "Active participant in Sensory Resilience cohort. Next clinic session Oct 12.",
    internalStaffNote: "Geriatric diversity quota satisfied. High compliance score.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 12, 2:00 PM",
    lastStatusChangedByName: "Dr. H. Whitman, MD",
    appointmentDate: "Oct 12 at 10:30 AM",
    createdAt: "Aug 25, 11:00 AM",
  },
  // Darius Washington on study_3 (Sleep Observational) -> under_review
  {
    id: "app_8",
    studyId: "study_3",
    profileId: "prof_darius",
    studyTitle: "National Digital Sleep & Circadian Rhythm Study",
    sponsorName: "BioVanguard Digital Health Institute",
    compensationAmount: 320,
    status: "under_review",
    qualificationScore: 95,
    answers: { q3_1: "yes", q3_2: "no", q3_3: "yes", q3_4: "no" },
    researcherNotes: "Urban tech professional with asthma. Oximetry tracking approved.",
    participantFacingNote: "Application under review. Coordinator is validating nocturnal sensor batch parameters.",
    internalStaffNote: "Pre-screen passed. High tech literacy.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 14, 9:00 AM",
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: undefined,
    createdAt: "Sep 13, 4:20 PM",
  },
  // Maria Santos on study_4 (Oral GLP-1) -> action_needed
  {
    id: "app_9",
    studyId: "study_4",
    profileId: "prof_maria",
    studyTitle: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist Trial",
    sponsorName: "Apex Pharma Therapeutics",
    compensationAmount: 1850,
    status: "action_needed",
    qualificationScore: 100,
    answers: { q4_1: "yes", q4_2: "no", q4_3: "no", q4_4: "yes" },
    researcherNotes: "Bilingual participant. Hypertension medication stable for >6 months.",
    participantFacingNote: "Please complete and upload your 7-day home blood pressure log before your intake visit.",
    internalStaffNote: "Spanish intake packet required.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 15, 10:00 AM",
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: "Oct 02 at 1:30 PM",
    createdAt: "Sep 08, 10:00 AM",
  },
  // James "Jim" O'Connor on study_3 (Sleep Observational) -> eligible_next_step
  {
    id: "app_10",
    studyId: "study_3",
    profileId: "prof_jim",
    studyTitle: "National Digital Sleep & Circadian Rhythm Study",
    sponsorName: "BioVanguard Digital Health Institute",
    compensationAmount: 320,
    status: "eligible_next_step",
    qualificationScore: 100,
    answers: { q3_1: "yes", q3_2: "no", q3_3: "yes", q3_4: "no" },
    researcherNotes: "Rural military veteran with diagnosed insomnia. Meets all criteria.",
    participantFacingNote: "Pre-screen verified! Please choose your 30-minute telehealth onboarding window.",
    internalStaffNote: "Eligible for rural veteran compensation bump.",
    assignedCoordinatorId: "coordinator_sarah",
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: "Sep 15, 11:30 AM",
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: "Sep 28 at 3:00 PM",
    createdAt: "Sep 07, 2:45 PM",
  },
];

export const INITIAL_TASKS: ParticipantTask[] = [
  {
    id: "task_1",
    applicationId: "app_1",
    profileKey: "prof_marcus",
    taskType: "confirm_availability",
    title: "Confirm Availability for Baseline Sensory Intake",
    description: "Coordinator Sarah Lindquist is scheduling your 90-minute initial sensory intake visit in Durham. Please select your preferred availability.",
    status: "pending",
    dueDate: "Sep 22, 2026",
    createdByName: "Sarah Lindquist, CRC",
    createdAt: "Sep 14, 10:30 AM",
  },
  {
    id: "task_2",
    applicationId: "app_1",
    profileKey: "prof_marcus",
    taskType: "confirm_contact",
    title: "Confirm Phone Number for Coordinator Callback",
    description: "Verify that (919) 555-0144 is the best phone number for Coordinator Sarah to reach you.",
    status: "completed",
    dueDate: "Sep 15, 2026",
    completedAt: "Sep 14, 12:15 PM",
    createdByName: "Sarah Lindquist, CRC",
    createdAt: "Sep 12, 9:00 AM",
  },
  {
    id: "task_3",
    applicationId: "app_3",
    profileKey: "prof_marcus",
    taskType: "review_study_details",
    title: "Review Digital Sleep Ring Setup Guide",
    description: "Familiarize yourself with how the smart sleep ring syncs via Bluetooth before hardware arrival.",
    status: "pending",
    dueDate: "Sep 25, 2026",
    createdByName: "Sarah Lindquist, CRC",
    createdAt: "Sep 13, 2:00 PM",
  },
  {
    id: "task_4",
    applicationId: "app_9",
    profileKey: "prof_maria",
    taskType: "document_upload",
    title: "Upload 7-Day Blood Pressure Log",
    description: "Record morning and evening blood pressure readings for 7 days and upload before clinic visit.",
    status: "pending",
    dueDate: "Sep 27, 2026",
    createdByName: "Sarah Lindquist, CRC",
    createdAt: "Sep 15, 10:00 AM",
  },
  {
    id: "task_5",
    applicationId: "app_10",
    profileKey: "prof_jim",
    taskType: "confirm_availability",
    title: "Select 30-Minute Telehealth Onboarding Window",
    description: "Coordinator Sarah Lindquist is scheduling your remote sleep study onboarding. Please choose a slot.",
    status: "pending",
    dueDate: "Sep 24, 2026",
    createdByName: "Sarah Lindquist, CRC",
    createdAt: "Sep 15, 11:30 AM",
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif_1",
    profileKey: "prof_marcus",
    eventType: "action_required",
    title: "Action Required: Baseline Sensory Intake",
    body: "Coordinator Sarah Lindquist requested availability for your first visit on the Healthy Aging study.",
    studyId: "study_1",
    applicationId: "app_1",
    taskId: "task_1",
    isRead: false,
    createdAt: "Sep 14, 10:30 AM",
  },
  {
    id: "notif_2",
    profileKey: "prof_marcus",
    eventType: "status_changed",
    title: "Enrolled: Blood Profile Study",
    body: "Congratulations, your enrollment in Phase A of the Longitudinal Blood Profiling study is confirmed.",
    studyId: "study_2",
    applicationId: "app_2",
    isRead: true,
    createdAt: "Sep 10, 11:00 AM",
  },
  {
    id: "notif_3",
    profileKey: "prof_marcus",
    eventType: "application_submitted",
    title: "Application Received: Digital Sleep Study",
    body: "Your pre-screener was received by BioVanguard Digital Health Institute.",
    studyId: "study_3",
    applicationId: "app_3",
    isRead: true,
    createdAt: "Sep 05, 6:40 PM",
  },
];

export const INITIAL_CONSENTS: ParticipantConsent[] = [
  {
    id: "consent_1",
    profileKey: "prof_marcus",
    consentType: "terms_of_service",
    version: "2026.1",
    isGranted: true,
    grantedAt: "Aug 01, 2026",
  },
  {
    id: "consent_2",
    profileKey: "prof_marcus",
    consentType: "privacy_policy",
    version: "2026.1",
    isGranted: true,
    grantedAt: "Aug 01, 2026",
  },
  {
    id: "consent_3",
    profileKey: "prof_marcus",
    consentType: "matching_communications",
    version: "2026.1",
    isGranted: true,
    grantedAt: "Aug 01, 2026",
  },
  {
    id: "consent_4",
    profileKey: "prof_marcus",
    consentType: "transactional_email",
    version: "2026.1",
    isGranted: true,
    grantedAt: "Aug 01, 2026",
  },
  {
    id: "consent_5",
    profileKey: "prof_marcus",
    consentType: "marketing_email",
    version: "2026.1",
    isGranted: false,
    grantedAt: "Aug 01, 2026",
    revokedAt: "Aug 01, 2026",
  },
  {
    id: "consent_6",
    profileKey: "prof_marcus",
    consentType: "sms_opt_in",
    version: "2026.1",
    isGranted: true,
    grantedAt: "Aug 01, 2026",
  },
];

export const INITIAL_REMINDERS: StudyReminder[] = [
  {
    id: "rem_1",
    applicationId: "app_2",
    studyTitle: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    title: "12-Hour Fasting & Appointment Check-in",
    scheduledFor: "Tuesday, Sep 15 • 8:15 AM",
    notes: "Remember: Do not consume food or juice after 8:00 PM the night prior. Water is encouraged. Bring your government photo ID.",
    isCompleted: false,
    channel: "in_app",
  },
  {
    id: "rem_2",
    applicationId: "app_1",
    studyTitle: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    title: "Coordinator Outreach & Consent Review",
    scheduledFor: "Expected within 48 hours",
    notes: "Coordinator Sarah Lindquist will phone to walk through the IRB informed consent packet.",
    isCompleted: false,
    channel: "sms",
  },
];

export const PI_ACCOUNTS: PIData[] = [
  {
    id: "pi_whitman",
    username: "pi_whitman",
    name: "Dr. H. Whitman, MD",
    title: "Professor of Medicine & Director",
    institution: "Triangle Center for Aging and Brain Sciences",
    studyId: "study_1",
    studySlug: "healthy-aging-sensory-resilience-study",
    studyTitle: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    compensation: "$650",
    irbNumber: "Pro00109482",
  },
  {
    id: "pi_vance",
    username: "pi_vance",
    name: "Dr. Elena Vance, MD",
    title: "Vice Chair of Clinical Endocrinology",
    institution: "Apex Pharma Therapeutics & Clinical Trials",
    studyId: "study_4",
    studySlug: "phase-2-oral-glp1-diabetes-trial",
    studyTitle: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist Trial",
    compensation: "$1,850",
    irbNumber: "Advarra-IRB-2026-0182",
  },
  {
    id: "pi_aris",
    username: "pi_aris",
    name: "Dr. Rachel Aris, MD, PhD",
    title: "Chief of Cellular Immunology",
    institution: "Triangle Thoracic & Surgical Immunology Core",
    studyId: "study_2",
    studySlug: "healthy-volunteer-immunology-blood-profile",
    studyTitle: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    compensation: "$250",
    irbNumber: "IRB-2026-00412",
  },
  {
    id: "pi_sterling",
    username: "pi_sterling",
    name: "Dr. Marcus Sterling, PhD",
    title: "Head of Behavioral Sleep Medicine",
    institution: "BioVanguard Digital Health Institute",
    studyId: "study_3",
    studySlug: "national-digital-sleep-circadian-study",
    studyTitle: "National Digital Sleep & Circadian Rhythm Study",
    compensation: "$320 + ring",
    irbNumber: "WCG-IRB-2025-9981",
  },
  {
    id: "pi_thorne",
    username: "pi_thorne",
    name: "Dr. Julian Thorne, PhD",
    title: "Associate Professor of Neuroeconomics",
    institution: "Carolina Institute for Neuroeconomics (BRIC)",
    studyId: "study_5",
    studySlug: "fmri-risk-evaluation-financial-decisions",
    studyTitle: "Neuroimaging of Risk Evaluation & Financial Decisions",
    compensation: "$350",
    irbNumber: "UNC-IRB-25-0814",
  },
  {
    id: "coordinator_sarah",
    username: "coordinator_sarah",
    name: "Sarah Lindquist, CRC",
    title: "Lead Clinical Research Coordinator",
    institution: "Triangle Clinical Trials Operations",
    studyId: "all",
    studySlug: "all",
    studyTitle: "All Active Portfolio Protocols (Lead Coordinator View)",
    compensation: "Multi-site",
    irbNumber: "IRB-PORTFOLIO",
  },
];
